---
- name: Install Docker, run echo-server containers, and configure NGINX
  hosts: manager
  become: true
  collections:
    - community.docker
  vars:
    docker_user: "sasha00a@yandex.ru"
    docker_password: "Alex000!!!SSS" 
    author_name: "Александр Суслов"
  tasks:

    - name: Ensure required packages are installed
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        state: present
        update_cache: yes

    - name: Install docker Python module for Ansible
      pip:
        name: docker
        executable: pip3

    - name: Create the keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to apt sources
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        mode: '0644'

    - name: Update apt package list
      apt:
        update_cache: yes
      
    - name: Install Docker and docker-compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Login to Docker registry
      community.docker.docker_login:
        registry_url: https://index.docker.io
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: Run 3 echo-server containers
      community.docker.docker_container:
        name: "echo-server-{{ item }}"
        image: selenesa/my-flask-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "800{{ item }}:8000"
        env:
          AUTHOR: "{{ author_name }}"
      loop: [1, 2, 3]

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Deploy custom nginx.conf
      copy:
        src: /home/selenesa/Desktop/cloudcamp/nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
