apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzZWxlbmVzYSIsInBhc3N3b3JkIjoiQWxleDAwMCEhIVNTUyIsImVtYWlsIjoic2FzaGEwMGFAeWFuZGV4LnJ1IiwiYXV0aCI6ImMyVnNaVzVsYzJFNlFXeGxlREF3TUNFaElWTlRVdz09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: venv
type: kubernetes.io/dockerconfigjson
